-- Intentionally empty.
--
-- Supabase runs this file after migrations during `supabase db reset`.
-- BruinLink's demo club records are seeded by
-- `migrations/20260513090000_init_bruinlink_schema.sql`, so this file must not
-- recreate the older pre-admin-review schema.
